# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.7.1
#
# <auto-generated>
#
# Generated from file `Coll.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Vocal
_M_Vocal = Ice.openModule('Vocal')
__name__ = 'Vocal'

if 'Track' not in _M_Vocal.__dict__:
    _M_Vocal.Track = Ice.createTempClass()
    class Track(object):
        def __init__(self, author='', title='', filepath='', duration=0):
            self.author = author
            self.title = title
            self.filepath = filepath
            self.duration = duration

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.author)
            _h = 5 * _h + Ice.getHash(self.title)
            _h = 5 * _h + Ice.getHash(self.filepath)
            _h = 5 * _h + Ice.getHash(self.duration)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_Vocal.Track):
                return NotImplemented
            else:
                if self.author is None or other.author is None:
                    if self.author != other.author:
                        return (-1 if self.author is None else 1)
                else:
                    if self.author < other.author:
                        return -1
                    elif self.author > other.author:
                        return 1
                if self.title is None or other.title is None:
                    if self.title != other.title:
                        return (-1 if self.title is None else 1)
                else:
                    if self.title < other.title:
                        return -1
                    elif self.title > other.title:
                        return 1
                if self.filepath is None or other.filepath is None:
                    if self.filepath != other.filepath:
                        return (-1 if self.filepath is None else 1)
                else:
                    if self.filepath < other.filepath:
                        return -1
                    elif self.filepath > other.filepath:
                        return 1
                if self.duration is None or other.duration is None:
                    if self.duration != other.duration:
                        return (-1 if self.duration is None else 1)
                else:
                    if self.duration < other.duration:
                        return -1
                    elif self.duration > other.duration:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_Vocal._t_Track)

        __repr__ = __str__

    _M_Vocal._t_Track = IcePy.defineStruct('::Vocal::Track', Track, (), (
        ('author', (), IcePy._t_string),
        ('title', (), IcePy._t_string),
        ('filepath', (), IcePy._t_string),
        ('duration', (), IcePy._t_int)
    ))

    _M_Vocal.Track = Track
    del Track

if '_t_Collection' not in _M_Vocal.__dict__:
    _M_Vocal._t_Collection = IcePy.defineSequence('::Vocal::Collection', (), _M_Vocal._t_Track)

_M_Vocal._t_Coll = IcePy.defineValue('::Vocal::Coll', Ice.Value, -1, (), False, True, None, ())

if 'CollPrx' not in _M_Vocal.__dict__:
    _M_Vocal.CollPrx = Ice.createTempClass()
    class CollPrx(Ice.ObjectPrx):

        def add(self, t, context=None):
            return _M_Vocal.Coll._op_add.invoke(self, ((t, ), context))

        def addAsync(self, t, context=None):
            return _M_Vocal.Coll._op_add.invokeAsync(self, ((t, ), context))

        def begin_add(self, t, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_add.begin(self, ((t, ), _response, _ex, _sent, context))

        def end_add(self, _r):
            return _M_Vocal.Coll._op_add.end(self, _r)

        def search(self, t, context=None):
            return _M_Vocal.Coll._op_search.invoke(self, ((t, ), context))

        def searchAsync(self, t, context=None):
            return _M_Vocal.Coll._op_search.invokeAsync(self, ((t, ), context))

        def begin_search(self, t, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_search.begin(self, ((t, ), _response, _ex, _sent, context))

        def end_search(self, _r):
            return _M_Vocal.Coll._op_search.end(self, _r)

        def startStream(self, t, context=None):
            return _M_Vocal.Coll._op_startStream.invoke(self, ((t, ), context))

        def startStreamAsync(self, t, context=None):
            return _M_Vocal.Coll._op_startStream.invokeAsync(self, ((t, ), context))

        def begin_startStream(self, t, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_startStream.begin(self, ((t, ), _response, _ex, _sent, context))

        def end_startStream(self, _r):
            return _M_Vocal.Coll._op_startStream.end(self, _r)

        def searchTrackAndStream(self, t, context=None):
            return _M_Vocal.Coll._op_searchTrackAndStream.invoke(self, ((t, ), context))

        def searchTrackAndStreamAsync(self, t, context=None):
            return _M_Vocal.Coll._op_searchTrackAndStream.invokeAsync(self, ((t, ), context))

        def begin_searchTrackAndStream(self, t, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_searchTrackAndStream.begin(self, ((t, ), _response, _ex, _sent, context))

        def end_searchTrackAndStream(self, _r):
            return _M_Vocal.Coll._op_searchTrackAndStream.end(self, _r)

        def pauseStream(self, context=None):
            return _M_Vocal.Coll._op_pauseStream.invoke(self, ((), context))

        def pauseStreamAsync(self, context=None):
            return _M_Vocal.Coll._op_pauseStream.invokeAsync(self, ((), context))

        def begin_pauseStream(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_pauseStream.begin(self, ((), _response, _ex, _sent, context))

        def end_pauseStream(self, _r):
            return _M_Vocal.Coll._op_pauseStream.end(self, _r)

        def resumeStream(self, context=None):
            return _M_Vocal.Coll._op_resumeStream.invoke(self, ((), context))

        def resumeStreamAsync(self, context=None):
            return _M_Vocal.Coll._op_resumeStream.invokeAsync(self, ((), context))

        def begin_resumeStream(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_resumeStream.begin(self, ((), _response, _ex, _sent, context))

        def end_resumeStream(self, _r):
            return _M_Vocal.Coll._op_resumeStream.end(self, _r)

        def stopStream(self, context=None):
            return _M_Vocal.Coll._op_stopStream.invoke(self, ((), context))

        def stopStreamAsync(self, context=None):
            return _M_Vocal.Coll._op_stopStream.invokeAsync(self, ((), context))

        def begin_stopStream(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Vocal.Coll._op_stopStream.begin(self, ((), _response, _ex, _sent, context))

        def end_stopStream(self, _r):
            return _M_Vocal.Coll._op_stopStream.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Vocal.CollPrx.ice_checkedCast(proxy, '::Vocal::Coll', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Vocal.CollPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Vocal::Coll'
    _M_Vocal._t_CollPrx = IcePy.defineProxy('::Vocal::Coll', CollPrx)

    _M_Vocal.CollPrx = CollPrx
    del CollPrx

    _M_Vocal.Coll = Ice.createTempClass()
    class Coll(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::Vocal::Coll')

        def ice_id(self, current=None):
            return '::Vocal::Coll'

        @staticmethod
        def ice_staticId():
            return '::Vocal::Coll'

        def add(self, t, current=None):
            raise NotImplementedError("servant method 'add' not implemented")

        def search(self, t, current=None):
            raise NotImplementedError("servant method 'search' not implemented")

        def startStream(self, t, current=None):
            raise NotImplementedError("servant method 'startStream' not implemented")

        def searchTrackAndStream(self, t, current=None):
            raise NotImplementedError("servant method 'searchTrackAndStream' not implemented")

        def pauseStream(self, current=None):
            raise NotImplementedError("servant method 'pauseStream' not implemented")

        def resumeStream(self, current=None):
            raise NotImplementedError("servant method 'resumeStream' not implemented")

        def stopStream(self, current=None):
            raise NotImplementedError("servant method 'stopStream' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Vocal._t_CollDisp)

        __repr__ = __str__

    _M_Vocal._t_CollDisp = IcePy.defineClass('::Vocal::Coll', Coll, (), None, ())
    Coll._ice_type = _M_Vocal._t_CollDisp

    Coll._op_add = IcePy.Operation('add', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Vocal._t_Track, False, 0),), (), None, ())
    Coll._op_search = IcePy.Operation('search', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Vocal._t_Track, False, 0),), (), ((), _M_Vocal._t_Collection, False, 0), ())
    Coll._op_startStream = IcePy.Operation('startStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Vocal._t_Track, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Coll._op_searchTrackAndStream = IcePy.Operation('searchTrackAndStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_Vocal._t_Track, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Coll._op_pauseStream = IcePy.Operation('pauseStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    Coll._op_resumeStream = IcePy.Operation('resumeStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())
    Coll._op_stopStream = IcePy.Operation('stopStream', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), None, ())

    _M_Vocal.Coll = Coll
    del Coll

# End of module Vocal
